name: demoadmin
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+12

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:  ^3.1.7
  fluttertoast: ^8.0.8
  #multi_image_picker: ^4.8.0
  #  firebase_storage: ^8.0.0 ****
  time_range_picker: ^2.0.1
  cached_network_image: ^3.2.0
  date_picker_timeline: ^1.2.1
  intl: ^0.17.0
  firebase_auth: ^1.0.1
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+1
  http: ^0.13.1
  flutter_absolute_path:
    git:
      url: https://github.com/ValeriusGC/flutter_absolute_path.git
  #date_range_picker: ^1.0.7
  #  date_range_picker:
  #    git:
  #      url: https://github.com/anicdh/date_range_picker.git
  #      ref: master
  flutter_svg: ^0.22.0
  flutter_quill: ^4.0.9
  # flutter_quill:
  #   git:
  #     url: https://github.com/singerdmx/flutter-quill
  #     ref: upgrade
  flutter_swipe_detector : ^2.0.0
  flutter_image_compress: ^1.0.0
  multi_image_picker2: ^5.0.0
  url_launcher: ^6.0.18
  pdf: ^3.7.1
  open_file: ^3.2.1
  permission_handler: ^8.3.0
  syncfusion_flutter_datepicker: ^19.4.50
  # flutter_string_encryption: ^0.3.1
  shared_preferences: ^2.0.13
  mailer: ^5.1.0
  # jitsi_meet: ^4.0.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^4.0.6
  flutter_launcher_icons: "^0.9.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/icon.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/icons/dr.png
    - assets/icons/teeth.svg
    - assets/icons/gallery.svg
    - assets/icons/appoin.svg
    - assets/icons/doct.svg
    - assets/icons/sch.svg
    - assets/icons/chat.svg
    - assets/icons/banner.svg
    - assets/icons/booking.svg
    - assets/icons/group.svg
    - assets/icons/timing.svg
    - assets/icons/bell.svg
    - assets/icons/error.svg
    - assets/icons/nodata.svg
    - assets/icons/docblog.svg
    - assets/icons/type.svg
    - assets/icons/dept.svg
    - assets/icons/testi.svg
    - assets/icons/hcity.svg
    - assets/icons/hospita.svg
    - assets/icons/online.png
    - assets/icons/offline.png
    - assets/icons/orderhistory.png
    - assets/icons/item.png
    # - assets/icons/icon.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   fonts:
  #     - family: Schyler
  #       fonts:
  #         - asset: fonts/Schyler-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #           style: italic
  #     - family: Trajan Pro
  fonts:
    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

